config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/\-]+/i
  }

  devise_for :users, path: 'account', controllers: {
    sessions: :sessions,
    passwords: :passwords,
  }

  resource :setting, only: [:show, :update] do
    get :password, on: :member
  end

  resources :sections, only: :show
  resources :topics, only: :show
  resources :photos

  get 'markdown', to: 'home#markdown', as: 'markdown'

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :site_configs
    resources :topics do
      member do
        post :undestroy
        post :action
      end
      post :preview, on: :collection
    end
    resources :nodes
    resources :sections
    resources :users, constraints: { id: /[#{User::LOGIN_FORMAT}]*/ } do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :stats
  end

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  # get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"
  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: "", as: "users"
  end

  match "*path", to: "home#error_404", via: :all
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user, optional: true

  validates_presence_of :image

  # 封面图
  mount_uploader :image, PhotoUploader
end

app/controllers/admin/photos_controller.rb
# frozen_string_literal: true

module Admin
  class PhotosController < Admin::ApplicationController
    before_action :set_photo, only: %i[show destroy]

    def index
      @photos = Photo.order(id: :desc).includes(:user).page(params[:page])
    end

    def create
      # 浮动窗口上传
      @photo = Photo.new
      @photo.image = params[:file]
      if @photo.image.blank?
        render json: { ok: false }, status: 400
        return
      end

      @photo.user_id = current_user.id
      if @photo.save
        render json: { ok: true, url: @photo.image.url(:large) }
      else
        render json: { ok: false }
      end
    end

    def destroy
      @photo.destroy
      redirect_to(admin_photos_url)
    end

    private

      def set_photo
        @photo = Photo.find(params[:id])
      end
  end
end

app/views/admin/photos/index.html.erb
<% content_for :sitemap do %>
  <span class="current"><%= t('admin.menu.photos') %></span>
<% end %>

<table class="table table-bordered table-striped table-condensed">
  <tr>
    <td>#</td>
    <td>预览</td>
    <td>上传者</td>
    <td></td>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.id %></td>
    <td><%= link_to image_tag(photo.image.url(:md), style: "width: 150px"), photo.image.url, target: "_blank" if !photo[:image].blank? %></td>
    <td><%= photo.user.login if !photo.user.blank? %></td>
    <td><%= link_to '', admin_photo_path(photo), 'data-confirm' => 'Are you sure?', method: :delete, class: "fa fa-trash" %></td>
  </tr>
<% end %>
</table>
<%= paginate @photos %>
<br />

<%= link_to 'New Photo', new_admin_photo_path %>

app/views/admin/photos/show.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_photos_path %>"><%= t("admin.menu.photos")%></a> <i class="fa fa-angle-right"></i> <span class="current"><%= t("admin.check_photo")%></span>
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @photo.user.login %>
</p>
<p>
    <%= image_tag(@photo.image.url) %>
</p>


<%= link_to 'Edit', edit_admin_photo_path(@photo) %> |
<%= link_to 'Back', admin_photos_path %>