config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/\-]+/i
  }

  devise_for :users, path: 'account', controllers: {
    sessions: :sessions,
    passwords: :passwords,
  }

  resource :setting, only: [:show, :update] do
    get :password, on: :member
  end

  resources :sections, only: :show
  resources :topics, only: :show
  resources :photos

  get 'markdown', to: 'home#markdown', as: 'markdown'

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :site_configs
    resources :topics do
      member do
        post :undestroy
        post :action
      end
      post :preview, on: :collection
    end
    resources :nodes
    resources :sections
    resources :users, constraints: { id: /[#{User::LOGIN_FORMAT}]*/ } do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :stats
  end

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  # get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"
  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: "", as: "users"
  end

  match "*path", to: "home#error_404", via: :all
end

app/models/topic.rb
class Topic < ApplicationRecord
  include SoftDelete, MarkdownBody, UserAvatarDelegate
  include Topic::Actions, Topic::AutoCorrect

  mount_uploader :banner, BannerUploader

  belongs_to :user, inverse_of: :topics
  belongs_to :node, counter_cache: true, required: false

  validates :user_id, :title, :body, :node_id, :summary, presence: true

  counter :hits, default: 0

  delegate :login, to: :user, prefix: true, allow_nil: true
  delegate :body, to: :last_reply, prefix: true, allow_nil: true

  before_save { self.node_name = node.try(:name) || "" }

  def letter_banner_url(size)
    path = LetterAvatar.generate('topic', size).sub("public/", "/")

    "#{Setting.base_url}#{path}"
  end
end

app/models/topic/actions.rb
# frozen_string_literal: true

class Topic
  module Actions
    extend ActiveSupport::Concern

    included do
      enum grade: { normal: 0, excellent: 1 }

      def excellent!
        update!(grade: :excellent)
      end

      def unexcellent!
        update!(grade: :normal)
      end

    end

    # 删除并记录删除人
    def destroy_by(user)
      return false if user.blank?
      update_attribute(:who_deleted, user.login)
      destroy
    end

    def destroy
      super
    end
  end
end

app/models/topic/auto_correct.rb
# frozen_string_literal: true

require "auto-space"

class Topic
  module AutoCorrect
    extend ActiveSupport::Concern

    CORRECT_CHARS = [
      ["［", "["],
      ["］", "]"],
      ["【", "["],
      ["】", "]"],
      ["（", "("],
      ["）", ")"]
    ]

    included do
      before_save :auto_correct_title
    end

    private
      def auto_correct_title
        return if title.blank?
        title.dup
        CORRECT_CHARS.each do |chars|
          title.gsub!(chars[0], chars[1])
        end
        title.auto_space!
      end
  end
end

app/models/topic/search.rb
# frozen_string_literal: true

class Topic
  module Search
    extend ActiveSupport::Concern

    included do
      mapping do
        indexes :title, term_vector: :yes
        indexes :body, term_vector: :yes
      end
    end

    def as_indexed_json(_options = {})
      {
        title: self.title,
        body: self.full_body
      }
    end

    def indexed_changed?
      saved_change_to_title? || saved_change_to_body?
    end

    def related_topics(limit: 5)
      opts = {
        query: {
          more_like_this: {
            fields: %i[title body],
            like: [
              {
                _index: self.class.index_name,
                _type: self.class.document_type,
                _id: id
              }
            ],
            min_term_freq: 2,
            min_doc_freq: 5
          }
        },
        size: limit
      }
      self.class.__elasticsearch__.search(opts).records.to_a
    rescue => e
      []
    end
  end
end

app/controllers/admin/topics_controller.rb
# frozen_string_literal: true

module Admin
  class TopicsController < Admin::ApplicationController
    before_action :set_topic, only: %i[show edit update destroy undestroy suggest unsuggest action]

    def index
      @topics = Topic.unscoped
      if params[:q].present?
        qstr = "%#{params[:q].downcase}%"
        @topics = @topics.where("title LIKE ?", qstr)
      end
      @topics = @topics.includes(:user).order(id: :desc).page(params[:page])
    end

    def show
    end

    def new
      @topic = Topic.new
    end

    def edit
    end

    def create
      @topic = Topic.new(topic_params)
      @topic.user_id = current_user.id
      @topic.node_id = params[:node] || topic_params[:node_id]

      if @topic.save
        redirect_to(admin_topics_path, notice: "Topic was successfully created.")
      else
        render action: "new"
      end
    end

    def update
      if @topic.update(topic_params)
        redirect_to(admin_topics_path, notice: "Topic was successfully updated.")
      else
        render action: "edit"
      end
    end

    def destroy
      @topic.destroy_by(current_user)

      redirect_to(admin_topics_path)
    end

    def preview
      @body = params[:body]

      respond_to do |format|
        format.json
      end
    end

    def undestroy
      @topic.update_attribute(:deleted_at, nil)
      redirect_to(admin_topics_path)
    end

    def action
      case params[:type]
      when "excellent"
        @topic.excellent!
        redirect_to admin_topics_path, notice: "加精成功。"
      when "normal"
        @topic.normal!
        redirect_to admin_topics_path, notice: "话题已恢复到普通评级。"
      end
    end

    private

    def set_topic
      @topic = Topic.unscoped.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title, :body, :node_id, :sort, :summary, :banner)
    end
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  def show
    @topic = Topic.unscoped.includes(:user).find(params[:id])
    render_404 if @topic.deleted?
  end

  private

    def set_topic
      @topic ||= Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

require "digest/md5"
module TopicsHelper
  include LetterAvatar::AvatarHelper

  def topic_favorite_tag(topic, opts = {})
    return "" if current_user.blank?
    opts[:class] ||= ""
    class_name = ""
    link_title = "收藏"
    if current_user&.favorite_topic?(topic)
      class_name = "active"
      link_title = "取消收藏"
    end

    icon = raw(content_tag("i", "", class: "fa fa-bookmark"))
    if opts[:class].present?
      class_name += " " + opts[:class]
    end

    link_to(raw("#{icon} 收藏"), "#", title: link_title, class: "bookmark #{class_name}", "data-id" => topic.id)
  end

  def topic_follow_tag(topic, opts = {})
    return "" if current_user.blank?
    return "" if topic.blank?
    return "" if owner?(topic)
    opts[:class] ||= ""
    class_name = "follow"
    class_name += " active" if current_user.follow_topic?(topic)
    if opts[:class].present?
      class_name += " " + opts[:class]
    end
    icon = content_tag("i", "", class: "fa fa-eye")
    link_to(raw("#{icon} 关注"), "#", "data-id" => topic.id, class: class_name)
  end

  def topic_title_tag(topic, opts = {})
    return t("topics.topic_was_deleted") if topic.blank?
    if opts[:reply]
      index = topic.floor_of_reply(opts[:reply])
      path = main_app.topic_path(topic, anchor: "reply#{index}")
    else
      path = main_app.topic_path(topic)
    end
    link_to(topic.title, path, title: topic.title)
  end

  def topic_excellent_tag(topic)
    return "" unless topic.excellent?
    content_tag(:i, "", title: "精华帖", class: "fa fa-diamond", data: { toggle: "tooltip" })
  end

  def topic_close_tag(topic)
    return "" unless topic.closed?
    content_tag(:i, "", title: "问题已解决／话题已结束讨论", class: "fa fa-check", data: { toggle: "tooltip" })
  end

  def render_node_name(name, id, node_id)
    link_to(name, main_app.section_path(id, category: node_id), class: "node")
  end

  def topic_banner_tag(topic, version = :md, link: true, timestamp: nil)
    width     = topic_banner_width_for_size(version)
    img_class = "media-object banner-#{width}"

    return image_tag("banner/#{version}.png", class: img_class, width: width, height: width * 0.7) if topic.blank?

    img =
      if topic.banner?
        image_url = topic.banner.url(version)
        image_url += "?t=#{topic.updated_at.to_i}" if timestamp
        image_tag(image_url, class: img_class, width: width, height: width * 0.6)
      else
        image_tag(topic.letter_banner_url(width * 2), class: img_class, width: width, height: width * 0.6)
      end

    html_options = {}
    html_options[:title] = topic.title

    if link
      link_to(raw(img), "/#{topic.title}", html_options)
    else
      raw img
    end
  end

  def topic_banner_width_for_size(size)
    case size
      when :xs then 16
      when :sm then 32
      when :md then 48
      when :lg then 200
      when :large then 600
      else size
    end
  end
end

app/views/admin/topics/_form.html.erb
<%= render 'node_selector', node: @topic.node %>

<%= form_for [:admin,@topic], class: "form", html: { tb: 'edit-topic', enctype: "multipart/form-data" } do |f| %>
  <%= render 'shared/error_messages', target: @topic %>
  <%= f.hidden_field :node_id %>

  <div class="form-group">
    <div class="input-group">
      <div class="input-group-prepend">
        <button type="button" class="btn btn-default" id="node-selector-button"
          data-toggle="modal" data-target="#node-selector">
          <%= @topic.node&.name || '选择节点...' %>
        </button>
      </div>
      <%= f.text_field :title, class: "form-control", placeholder: "在这里填写标题" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :sort %>
    <%= f.text_field :sort, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <div class="form-text">选择上传banner</div>
    <%= f.file_field :banner %>
  </div>
  <div class="col-sm-3">
    <div class="form-group avatar-preview" style="text-align: center;">
      <%= topic_banner_tag(@topic, :lg, link: false) %>
    </div>
  </div>

  <%= render "/shared/editor_toolbar" %>

  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control closewarning", rows: 20 %>
  </div>

  <div class="form-actions hide-ios">
    <%= f.submit t("common.save"), class: "btn btn-primary", 'data-disable-with' => t("common.saving"), 'data-tb' => "save-topic" %>

    <div class="pull-right hide-ios"><a href="/markdown" target="_blank"><i class="fa fa-tip"></i> 排版说明</a></div>
  </div>
<% end %>

app/views/admin/topics/_node_selector.html.erb
<div class="modal" id="node-selector" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title">讨论区节点</div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render '/shared/index_sections' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/topics/_related_topics.html.erb
<% cache([@topic, 'related_topic', Date.current]) do %>
  <% if @topic.related_topics.present? %>
    <div class="card">
      <div class="card-header">相关话题</div>
      <ul class="list-group list-group-flush">
        <% @topic.related_topics.each do |topic| %>
          <li class="list-group-item"><%= link_to topic.title, topic %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/admin/topics/_topic.html.erb
<% cache([topic, topic.user_avatar_raw, suggest]) do %>
<div class="topic media topic-<%= topic.id %>">
  <div class="avatar">
    <%= user_avatar_tag(topic.user, :md) %>
  </div>
  <div class="infos media-body">
    <div class="title media-heading">
      <%= link_to(main_app.topic_path(topic), title: topic.title) do %>
        <%= raw content_tag(:span, topic.node_name, class: 'node') %>
        <%= topic.title %>
      <% end %>
      <% if suggest %>
        <i class="fa fa-angle-double-up" title="置顶"></i>
      <% end %>
      <%= topic_excellent_tag(topic) %>
      <%= topic_close_tag(topic) %>
    </div>
    <div class="info">
      <%= user_name_tag(topic.user) %>
      <span class="hidden-mobile">
      •
      <% if topic.last_reply_user_login.blank? %>
        <%= raw t("common.created_at", time: timeago(topic.created_at))%>
      <% else %>
        <%= t("common.last_by")%> <%= user_name_tag(topic.last_reply_user_login) %> <%= raw t("common.reply_at", time: timeago(topic.replied_at))%>
      <% end %>
      </span>
    </div>
  </div>
  <div class="count media-right">
    <% if topic.replies_count > 0 %>
      <%= link_to(topic.replies_count,"#{main_app.topic_path(topic)}#reply-#{topic.last_reply_id}", class: "state-false") %>
    <% end %>
  </div>
</div>
<% end %>

app/views/admin/topics/_topic_sidebar.html.erb
<div id="topic-sidebar" data-spy="affix" data-offset-bottom="65">
  <div class="card">
    <div class="card-body">
      <a href="#" class="btn btn-default btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
      <hr />
      <div class="group opts">
        <div>
          <%= link_to raw("<i class='fa fa-arrow-circle-left'></i> 返回"), admin_topics_path, method: 'get', title: "返回" %>
          <%= link_to raw('<i class="fa fa-pencil"></i> 编辑'), edit_admin_topic_path(@topic), title: "修改本帖" %>
          <%= link_to raw('<i class="fa fa-trash"></i> 删除'), admin_topic_path(@topic.id), method: :delete, 'data-confirm' => t("common.confirm_delete"), title: "删除本帖", remote: true %>
        </div>
      </div>
      <a href="#" class="btn btn-default btn-sm btn-block btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
    </div>
  </div>
</div>

app/views/admin/topics/edit.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_topics_path %>"><%= t("admin.menu.topics")%></a> <i class="fa fa-angle-right"></i> <span class="current"><%= t("common.edit")%></span>
<% end %>
<h1><%= t("common.edit")%><%= t("admin.menu.topics") %></h1>

<%= render 'form' %>

app/views/admin/topics/index.html.erb
<% content_for :sitemap do %>
  <span class="current"><%= t("admin.menu.topics")%></span>
<% end %>

<div class="toolbar">
  <form class="form-inline" action="<%= admin_topics_path %>">
    <div class="form-group mr-sm-2">
      <input type="text" name="q" class="form-control" value="<%= params[:q] %>" placeholder="标题" />
    </div>
    <div class="form-group mr-sm-2">
      <input type="text" name="login" class="form-control" value="<%= params[:login] %>" placeholder="用户名" />
    </div>
    <button class="btn btn-default">搜索</button>
  </form>
</div>

<div class="toolbar">
  <%= link_to '新建话题', new_admin_topic_path, class: "btn btn-default" %>
</div>


<table class="table table-bordered table-striped table-condensed">
  <tr class="head">
    <td class="first">#</td>
    <td style="width:300px">标题</td>
    <td>节点</td>
    <td>发布人</td>
    <td>时间</td>
    <td>优先级</td>
    <td style="width:100px"></td>
  </tr>

  <% @topics.each do |topic| %>
    <tr class="<%= 'deleted' if !topic.deleted_at.blank? %>">
      <td class="first"><%= topic.id %></td>
      <td>
        <%= link_to truncate(topic.title, length: 30), admin_topic_path(topic), target: "_blank" %>
      </td>
      <td><%= topic.node_name %></td>
      <td><%= user_name_tag(topic.user) %></td>
      <td>
        <% if topic.deleted_at.blank? %>
          <%= l topic.created_at, format: :short %>
        <% else %>
          <%= link_to topic.who_deleted, user_path(topic.who_deleted) if not topic.who_deleted.blank? %> 删除于 <br />
          <%= l topic.deleted_at, format: :short %>
        <% end %>
      </td>
      <td><%= topic.sort %></td>
      <td>
        <% if topic.excellent? %>
          <%= link_to raw("<i class='fa fa-thumbs-o-down'></i> 取消加精"), action_admin_topic_path(topic, type: 'normal'), method: "post", remote: true %>
        <% else %>
          <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_admin_topic_path(topic, type: 'excellent'), method: "post", remote: true %>
        <% end %>
        <%= link_to "", edit_admin_topic_path(topic), class: "fa fa-pencil" %>
        <% if topic.deleted_at.blank? %>
          <%= link_to "", admin_topic_path(topic), 'data-confirm' => 'Are you sure?', method: :delete, class: "fa fa-trash" %>
        <% else %>
          <%= link_to "", undestroy_admin_topic_path(topic), title: t("common.undelete"), 'data-confirm' => 'Are you sure?', method: :post, class: "fa fa-undo" %>
        <% end %>
      </td>

    </tr>
  <% end %>
</table>
<%= paginate @topics %>

app/views/admin/topics/new.html.erb
<% title_tag t('topics.new_topic') %>

<div class="card">
  <div class="card-header hide-ios"><%= t('topics.new_topic') %></div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/topics/show.html.erb
<% title_tag @topic.title %>

<div class="row">
  <div class="col-md-9">
    <div class="topic-detail card">
      <%= render partial: "topics/topic_info", locals: { topic: @topic } %>

      <div class="card-body markdown markdown-toc">
        <div class="form-group avatar-preview" style="margin-bottom: 30px">
          <%= topic_banner_tag(@topic, :large) %>
        </div>
        <%= raw Setting.before_topic_html %>

        <%= @topic.body_html %>

        <%= raw Setting.after_topic_html %>
      </div>
    </div>
  </div>

  <div class="sidebar hidden-mobile col-md-3">
    <%= render 'topic_sidebar' %>
  </div>
</div>