config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/\-]+/i
  }

  devise_for :users, path: 'account', controllers: {
    sessions: :sessions,
    passwords: :passwords,
  }

  resource :setting, only: [:show, :update] do
    get :password, on: :member
  end

  resources :sections, only: :show
  resources :topics, only: :show
  resources :photos

  get 'markdown', to: 'home#markdown', as: 'markdown'

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :site_configs
    resources :topics do
      member do
        post :undestroy
        post :action
      end
      post :preview, on: :collection
    end
    resources :nodes
    resources :sections
    resources :users, constraints: { id: /[#{User::LOGIN_FORMAT}]*/ } do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :stats
  end

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  # get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"
  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: "", as: "users"
  end

  match "*path", to: "home#error_404", via: :all
end

app/models/section.rb
class Section < ApplicationRecord
  acts_as_paranoid
  second_level_cache expires_in: 2.weeks

  has_many :nodes, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  default_scope -> { order(sort: :desc) }

  form_select :name
end

app/controllers/admin/sections_controller.rb
# frozen_string_literal: true

module Admin
  class SectionsController < Admin::ApplicationController
    before_action :set_section, only: %i[show edit update destroy]

    def index
      @sections = Section.all
    end

    def show
    end

    def new
      @section = Section.new
    end

    def edit
    end

    def create
      @section = Section.new(params[:section].permit!)

      if @section.save
        redirect_to(admin_sections_path, notice: "Section was successfully created.")
      else
        render action: "new"
      end
    end

    def update
      if @section.update(params[:section].permit!)
        redirect_to(admin_sections_path, notice: "Section was successfully updated.")
      else
        render action: "edit"
      end
    end

    def destroy
      @section.destroy

      redirect_to(admin_sections_url)
    end

    private

      def set_section
        @section = Section.find(params[:id])
      end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find(params[:id])
    @nodes   = @section.nodes.order(sort: :desc, id: :desc)
    node     = params[:category].nil? ? @nodes.first : @nodes.where(id: params[:category]).first

    return render_404 if node.nil?
    @topics  = node.topics.includes(:user).order(sort: :asc).page(params[:page])
  end
end

app/views/admin/sections/_form.html.erb
<%= form_for [:admin, @section] do |f| %>
  <%= render 'shared/error_messages', target: @section %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sort %>
    <%= f.text_field :sort, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit t("common.save"), class: "btn btn-primary", 'data-disable-with' => t("common.saving") %>
  </div>
<% end %>

app/views/admin/sections/edit.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_sections_path %>"><%= t("admin.menu.sections") %></a> <i class="fa fa-angle-right"></i> <span class="current"><%= t("common.edit") %></span>
<% end %>
<h1>Editing section</h1>

<%= render 'form' %>

app/views/admin/sections/index.html.erb
<% content_for :sitemap do %>
  <span class="current"><%= t("admin.menu.sections") %></span>
<% end %>

<div class="toolbar">
  <%= link_to '新建分类', new_admin_section_path, class: "btn btn-default" %>
</div>

<table class="table table-bordered table-striped table-condensed">
  <tr class="head">
    <td class="first">#</td>
    <td>名称</td>
    <td>排序</td>
    <td></td>
  </tr>

<% @sections.each do |section| %>
  <tr>

    <td class="first"><%= section.id %></td>
    <td><%= section.name %></td>
    <td><%= section.sort %></td>
    <td><%= link_to '', edit_admin_section_path(section), class: "fa fa-pencil" %>
    <%= link_to '', admin_section_path(section), 'data-confirm' => '确定要删除吗?', method: :delete, class: "fa fa-trash" %></td>
  </tr>
<% end %>
</table>

app/views/admin/sections/new.html.erb
<% content_for :sitemap do %>
  <a href="<%= admin_sections_path %>"><%= t("admin.menu.sections") %></a> <i class="fa fa-angle-right"></i> <span class="current"><%= t("common.create") %></span>
<% end %>

<h1>新建分类</h1>

<%= render 'form' %>