config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/\-]+/i
  }

  devise_for :users, path: 'account', controllers: {
    sessions: :sessions,
    passwords: :passwords,
  }

  resource :setting, only: [:show, :update] do
    get :password, on: :member
  end

  resources :sections, only: :show
  resources :topics, only: :show
  resources :photos

  get 'markdown', to: 'home#markdown', as: 'markdown'

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :site_configs
    resources :topics do
      member do
        post :undestroy
        post :action
      end
      post :preview, on: :collection
    end
    resources :nodes
    resources :sections
    resources :users, constraints: { id: /[#{User::LOGIN_FORMAT}]*/ } do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :stats
  end

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  # get "users/city/:id", to: "users#city", as: "location_users"
  get "users", to: "users#index", as: "users"
  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: "", as: "users"
  end

  match "*path", to: "home#error_404", via: :all
end

app/views/shared/_editor_toolbar.html.erb
<div class="editor-toolbar clearfix">
  <div class="reply-to pull-right" style="display:none;">
    <i class="fa fa-mail-reply" title="回复"></i>
    <a href="#" class="user"></a>
    <a href="#" class="close"><i class="fa fa-close"></i></a>
  </div>
  <div class="opts">
    <a href="#" class="nav-link pickup-emoji"><i class="fa fa-smile-o"></i></a>
    <% if Setting.has_module? 'editor.code' %>
    <span class="dropdown" id="dropdown-insert-codes">
      <a href="#editor-toolbar-insert-code" class="nav-link dropdown-toggle" data-toggle="dropdown" title="<%= t("common.editor_insert_codes") %>"><i class="fa fa-code"></i></a>
      <div class="dropdown-menu insert-codes" aria-labelledby="dropdown-insert-codes">
        <%= insert_code_menu_items_tag %>
      </div>
    </span>
    <% end %>
    <%= link_to icon_tag("image"), "#", id: "editor-upload-image", title: t("common.editor_add_image"), class: "nav-link" %>
    <a href="#" class="nav-link preview"><%= t("common.editor_toolbar_preview") %></a>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="alert alert-block alert-danger">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <div><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></div>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_index_sections.html.erb
<div class="index-sections card">
  <div class="card-header"><%= t("common.index_node_navigation")%></div>
  <div class="card-body">
    <div class="row node-list">
      <% Section.includes(:nodes).all.each do |section| %>
      <div class="node media">
        <label class="mr-2 media-left"><%= section.name %></label>
        <span class="nodes media-body">
          <% section.nodes.sorted.each do |node| %>
            <span class="name"><%= link_to(node.name, admin_nodes_path(node), title: node.name, data: { id: node.id })%></span>
          <% end %>
        </span>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<ul id="main-nav-menu" class="navbar-nav d-flex">
  <% Section.all.each do |section| %>
    <li class="nav-item">
      <% if section.id == params[:id].to_i %>
        <%= link_to section.name, section_path(section, category: section.nodes.order(sort: :desc, id: :desc)&.first&.id), class: "nav-link active" %>
      <% else %>
        <%= link_to section.name, section_path(section, category: section.nodes.order(sort: :desc, id: :desc)&.first&.id), class: "nav-link " %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_sidebar_box_tips.html.erb
<div class="card">
  <div class="card-header">小帖士</div>
  <div class="card-body">
    <%= random_tips %>
  </div>
</div>

app/views/shared/_sidebar_for_topic_index.html.erb
<%= render "/shared/sidebar_box_tips" %>

<%= raw Setting.topic_index_sidebar_html %>

<% cache(["sidebar_statistics",Time.now.strftime("%Y-%m-%d %H")]) do %>
  <div class="card">
    <div class="card-header"><%= "热门新闻" %></div>
    <ul class="list-group list-group-flush">
      <% Topic.excellent.each do |topic| %>
        <li class="list-group-item">
          <%= topic_banner_tag(topic, :md) %>
          <%= link_to topic.title, topic_path(topic) %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_usernav.html.erb
<ul class="nav navbar-nav user-bar align-items-center justify-content-end">
  <% if current_user %>
    <li class="nav-item dropdown dropdown-avatar">
      <a href="#" class="dropdown-toggle nav-link" id="navbar-user-menu" data-toggle="dropdown" role="button" aria-expanded="false">
        <%= user_avatar_tag(current_user, :sm, link: false) %>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-user-menu">
        <div class="dropdown-divider"></div>
        <%= link_to t("menu.edit_account_path"), main_app.setting_path, class: "dropdown-item" %>

        <% if admin? %>
          <div class="dropdown-divider"></div>
          <% if params[:controller].start_with?("admin/") %>
            <%= link_to "回到前台", main_app.root_path, class: "dropdown-item" %>
          <% else %>
            <%= link_to "管理后台", main_app.admin_root_path, class: "dropdown-item" %>
          <% end %>
        <% end %>

        <div class="dropdown-divider"></div>
        <%= link_to t("common.logout"), main_app.destroy_user_session_path, method: "delete", class: "dropdown-item" %>
      </div>
    </li>
  <% else %>
    <li class="nav-item"><%= link_to t("common.login"), main_app.new_user_session_path, class: "nav-link" %></li>
  <% end %>
</ul>